version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.entrypoints.api.app
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
